### ISSUE TITLE
Can you add a option for pan-to-drag to lock to image?

### ISSUE THREAD

**Issue by fire838** [occivink/mpv-image-viewer#12]
Please add a option for pan-to-drag to not go out of borders, like Irfanview when zoomed and fullscreened. I know pan-follows-cursor exist but it's not as smooth as pan-to-drag.

Included a video if you don't understand: https://streamable.com/pm6q2

**Comment by occivink** [comment]
that makes sense, I will look into it

**Comment by occivink** [comment]
You can set the margin option to 0 if you want the same behavior as with irfanview

**Comment by fire838** [comment]
Good job.

Can you add a option to keep the image locked in centre and only allow to pan up and down when margins are visible (full screened). But allow to pan all 4 direction when really zoomed, no margins shown (how it is right now).

Refer to Irfanview fullscreen mode.

**Comment by occivink** [comment]
So a drag-to-pan counterpart to `pan_follows_cursor_move_if_full_view`? Is there a need for allowing up-down if the image is entirely visible? I don't really feel like special-casing up-down versus left-right

**Comment by fire838** [comment]
Don't allow the image to be dragged around the margins at all by locking it in the centre.  Pretty much its making pan-to-drag behave exactly like pan-follows-cursor.
