### ISSUE TITLE
Add vim bindings

### ISSUE THREAD

**Issue by nonetrix** [occivink/mpv-image-viewer#30]
Recently switched over to this because IMV seem unmaintained and won't install anymore on NixOS because of a library it uses has CVEs, and it doesn't seem worth risking bypassing it. One feature I have missed from switching is the ability to use vim keys to pan etc. E.g. h,j,k,l to pan the image

**Comment by nonetrix** [comment]
wait sorry wrong project

**Comment by NormTurtle** [comment]
@nonetrix share which you picked tho?

**Comment by nonetrix** [comment]
woelper/oculante might still try out MPV as it seems overkill for my needs
