### ISSUE TITLE
The mpv window repositions to center when resizing (since mpv 0.38.0)

### ISSUE THREAD

**Issue by hakonrk** [occivink/mpv-image-viewer#31]
## System info:

- mpv version: 0.38.0
- OS: Windows 11 version 23H2 (OS Build 22631.3447)
- Source of the mpv binary: mpv-0.38.0-x86_64.7z (downloaded from the official mpv github repo)
- mpv-image-viewer version: master (efc82147cba4809f22e9afae6ed7a41ad9794ffd)

## Steps to reproduce:

- Open mpv.exe
- Resize the mpv application window

## Expected behavior:

The mpv window should resize like any other application.

## Actual behavior:

The mpv window moves itself to the center when its size changes. See the attached video recording, which compares the resizing behavior with mpv 0.37.0 and mpv 0.38.0. If I disable mpv-image-viewer, both versions of mpv resize normally.

https://github.com/occivink/mpv-image-viewer/assets/24655611/3fcb5d4e-6ee1-447a-8667-07da1a72d229

**Comment by occivink** [comment]
I think this is something the `freeze-window` script is doing. It's anyway superseded by the (somewhat recently added) option `auto-window-resize`

**Comment by hakonrk** [comment]
Thanks, removing `freeze-window.lua` did fix the problem.
