### ISSUE TITLE
Browsing the directory

### ISSUE THREAD

**Issue by smarek** [occivink/mpv-image-viewer#5]
When launching mvi through xdg-open (see #4 ), and the same when launching mvi through cli, it will only play the file(s) we opened.

Usually image browsers do support switching between images (in alphabetical order) in the same directory right away.

I've very naive solution to this, which uses last file from provided arguments and adds whole directory to allow browsing (sincerely from the first file in alphabetical order away)

It would be cool, if the mvi, when launched with single file argument, added whole directory as playlist and switched to file in argument in created playlist appropriately.
I think this would not work well when launched with multiple arguments (disregard if those are files or folders)

My solution:
```
#!/bin/bash

LASTARG="${@: -1}"
REAL=$(realpath "$LASTARG")
DIR=$(dirname "$REAL")
if [[ -f $REAL ]];
then
  ADD=$DIR
else
  ADD=""
fi

# will pass original arguments and then folder determined from last argument, if determined
mpv --config-dir=$HOME/.config/mvi/ "$@" "$ADD"
```

**Comment by occivink** [comment]
I recommend using the [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) script from mpv for this. (also thanks for the .desktop file issue, I'll address it at some point)

**Comment by smarek** [comment]
Thank you, that seems like the best way, I've added the file in ~/.config/mvi/scripts/ directory and it autoloaded, sadly it does not work.
Check on line 105 ( https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua#L105 ) will return immediately, and will not add surrounding files to current playlist.
You might know why?

(cheers, #4 was fun, it as well might not be integrated, i'm just happy it works in my case)

**Comment by occivink** [comment]
It looks like the script only runs when the file you're playing matches any of these extensions, try changing that?
https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua#L25-L28

**Comment by smarek** [comment]
Thank you, works correctly after adding appropriate extensions, could you probably include modified script in your repo?

**Comment by occivink** [comment]
I don't really like the idea of duplicating the script, but I think the mpv people would accept a pull request that makes these changes, if you feel like submitting one.

**Comment by smarek** [comment]
We could try, however since MPV is video player, i don't think they'll accept it. Maybe patch file and script would suit you better?

**Comment by occivink** [comment]
I'd only accept a patch if they explicitly refused to add these formats. I think it's just as in scope as audio formats.

**Comment by smarek** [comment]
Well https://github.com/mpv-player/mpv/pull/6990 got merged, so I guess we could provide instructions on how to use / configure that autoload now?

**Comment by smarek** [comment]
Well since it got accepted with default presets (images on) not much, maybe
just the default script-opts disabling audio and video files for mvi
purposes.
