### ISSUE TITLE
Little issue while reading manga.

### ISSUE THREAD

**Issue by mac1202** [occivink/mpv-image-viewer#7]
Hi using mvi for reading online manga I have a little issue. I zoom image for better readability so I scroll down to read the full page. The issue is when I switch to the next page the view is at the bottom of the new page. So everytime i switch to a new page I have to scroll to the top. Is there a way to improve this behaviour ?

**Comment by occivink** [comment]
Hi,

You can use `detect-image.lua` combined with `image-positioning.lua` to that effect.
By adding `command_on_image_loaded=script-message align-border 0 1` to your `detect_image.conf`, the panning will be set to the top of the image every time it changes

I have a [similar setup in my configuration](https://github.com/occivink/config/blob/master/.config/mvi/mpv.conf#L41), which I use in a specific profile.

**Comment by mac1202** [comment]
Thanks that exactly what I wanted to do.
